name: E2E tests
on: push
jobs:
  chrome:
    runs-on: ubuntu-22.04
    name: E2E on Chrome
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-node@6
        with:
          node-version: latest
      - uses: cypress-io/github-action@v7
