name: E2E tests
on: push
permissions:
  contents: read
jobs:
  chrome:
    runs-on: ubuntu-24.04
    name: E2E on Chrome
    timeout-minutes: 90
    env:
      CYPRESS_SKIP_JPETSTORE: true
    steps:
      - uses: actions/checkout@v6
      - uses: cypress-io/github-action@v7
        with:
          browser: chrome
